services:
  frontend:
    image: "sumith783/career-forge-frontend:latest"
    container_name: career-forge-frontend
    ports:
      - "80:3000"
    networks:
      - frontend-nw

networks:
  frontend-nw:
    driver: bridge