services:
  frontend:
    image: "sumith783/career-forge-frontend:latest"
    container_name: career-forge-frontend
    ports:
      - "80:3000"
    networks:
      - frontend


  # admin-service:
  #   image: "sumith783/career-forge-AdminService:latest"
  #   container_name: admin-service
  #   ports:
  #     - "8071:3001"
  #   extends:
  #     file: common-config.yaml
  #     service: microservice-base-config

networks:
  frontend:
    driver: bridge