apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.yaml: |
    mongodb:
      uri: "mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.resphjl.mongodb.net/carrerforge"
